export const IIDX_LEVELS: BPI_CALCABLE_LEVELS[] = ["11", "12"] as const;
export const IIDX_DIFFICULTIES: BPI_CALCABLE_DIFFICULTIES[] = [
  "HYPER",
  "ANOTHER",
  "LEGGENDARIA",
] as const;

export type BPI_CALCABLE_LEVELS = "11" | "12";
export type BPI_CALCABLE_DIFFICULTIES = "HYPER" | "ANOTHER" | "LEGGENDARIA";
