/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import { AllDifficulties } from "./songs/allSongs";

export interface Database {
  songs: Songs;
  songDef: SongDef;
  users: Users;
  scores: Scores;
  logs: Logs;
  userStatusLogs: UserStatusLogs;
  apiKeys: ApiKeys;
  follows: Follows;
  userRadarCache: UserRadarCache;
  notifications: Notifications;
  allSongs: AllSongsTable;
  allScores: AllScoresTable;
  // 追加: 暫定/バックアップ用テーブル
  bkScores: BkScores;
  bkUsers: BkUsers;
}

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface ApiKeys {
  createdAt: Generated<Date>;
  id: Generated<number>;
  key: string;
  userId: string;
}

export interface BkScores {
  bpi: Generated<Decimal | null>;
  clearState: Generated<number | null>;
  createdAt: Generated<Date | null>;
  difficulty: string;
  difficultyLevel: Generated<number | null>;
  exScore: number;
  lastPlayed: Generated<Date | null>;
  logId: Generated<number>;
  missCount: Generated<number | null>;
  title: string;
  userId: string;
  version: Generated<string | null>;
}

export interface BkUsers {
  arenarank: Generated<string | null>;
  currentTotalBpi: Generated<Decimal | null>;
  userId: string;
  userName: string;
}

export interface Follows {
  createdAt: Generated<Date>;
  followerId: string;
  followingId: string;
  id: Generated<number>;
}

export interface Logs {
  /**
   * 一括更新を識別するユニークなID
   */
  batchId: string;
  createdAt: Generated<Date>;
  id: Generated<number>;
  totalBpi: number;
  userId: string;
  version: string;
}

export interface Notifications {
  lastReadAt: Generated<Date>;
  userId: string;
}

export interface Scores {
  batchId: Generated<string | null>;
  bpi: Generated<number | null>;
  clearState: Generated<string | null>;
  createdAt: Generated<Date>;
  definitionId: number;
  exScore: number;
  lastPlayed: Generated<Date>;
  logId: Generated<number>;
  missCount: Generated<number | null>;
  songId: number;
  userId: string;
  version: string;
}

export interface SongDef {
  coef: Generated<number | null>;
  defId: Generated<number>;
  isCurrent: Generated<number | null>;
  kaidenAvg: number;
  songId: number;
  updatedAt: Generated<Date>;
  wrScore: number;
}

export interface Songs {
  bpm: string;
  createdAt: Generated<Date>;
  /**
   * 楽曲が削除されたバージョンを指定(このバージョン以降では投入しない)
   */
  deletedAt: Generated<string | null>;
  difficulty: string;
  difficultyLevel: number;
  notes: number;
  releasedVersion: Generated<number | null>;
  songId: Generated<number>;
  textage: string;
  title: string;
}

export interface UserRadarCache {
  charge: Generated<Decimal | null>;
  chord: Generated<Decimal | null>;
  notes: Generated<Decimal | null>;
  peak: Generated<Decimal | null>;
  scratch: Generated<Decimal | null>;
  soflan: Generated<Decimal | null>;
  totalBpi: Generated<Decimal | null>;
  updatedAt: Generated<Date | null>;
  userId: string;
  version: string;
}

export interface Users {
  createdAt: Generated<Date | null>;
  iidxId: Generated<string | null>;
  isPublic: number;
  profileImage: Generated<string | null>;
  profileText: Generated<string | null>;
  updatedAt: Generated<Date | null>;
  userId: string;
  userName: string;
  xId: Generated<string | null>;
}

export interface UserStatusLogs {
  arenaRank: Generated<string | null>;
  batchId: Generated<string | null>;
  createdAt: Generated<Date>;
  id: Generated<number>;
  totalBpi: Decimal;
  updatedAt: Generated<Date>;
  userId: string;
  version: string;
}

export interface AllSongsTable {
  songId: Generated<number>;
  title: string;
  notes: number;
  bpm: string;
  difficulty: AllDifficulties;
  difficultyLevel: number;
  textage: string;
  createdAt: Generated<Date>;
  deletedAt: string | null;
  releasedVersion: number | null;
}

export interface AllScoresTable {
  logId: Generated<number>;
  userId: string;
  songId: number;
  definitionId: number;
  exScore: number;
  bpi: number | null;
  clearState: string | null;
  missCount: number | null;
  createdAt: Generated<Date>;
  lastPlayed: Generated<Date>;
  version: string;
  batchId: string | null;
}

export type UserStatusLog = Selectable<UserStatusLogs>;
export type NewUserStatusLog = Insertable<UserStatusLogs>;
export type TotalBPILog = Selectable<Logs>;
export type NewTotalBPILog = Insertable<Logs>;
export type ApiKey = Selectable<ApiKeys>;
export type NewApiKey = Insertable<ApiKeys>;
export type ApiKeyUpdate = Updateable<ApiKeys>;
export type BkScore = Selectable<BkScores>;
export type NewBkScore = Insertable<BkScores>;
export type BkUser = Selectable<BkUsers>;
export type NewBkUser = Insertable<BkUsers>;
export type Song = Selectable<Songs>;
export type User = Selectable<Users>;
export type Score = Selectable<Scores>;
export type NewScore = Insertable<Scores>;
export type Notification = Selectable<Notifications>;
export type NewNotification = Insertable<Notifications>;
export type NotificationUpdate = Updateable<Notifications>;
export type AllSongs = Selectable<AllSongsTable>;
export type NewAllSongs = Insertable<AllSongsTable>;
export type AllSongsUpdate = Updateable<AllSongsTable>;
export type AllScores = Selectable<AllScoresTable>;
export type NewAllScores = Insertable<AllScoresTable>;
export type AllScoresUpdate = Updateable<AllScoresTable>;
