import Head from "next/head";
import { LoginButtons } from "@/components/partials/LogIn";
import { Container, Heading, Separator, Spinner, Text } from "@chakra-ui/react";
import LoginPage from "@/components/partials/LogIn/page";
import RegistrationFlow from "@/components/partials/Modal/accountSettings";
import { UserProvider, useUser } from "@/contexts/users/UserContext";

export default function Home() {
  const { user, isLoading, fbUser, error } = useUser();
  if (isLoading) {
    return (
      <Container
        maxW={"100vw"}
        w={"100vw"}
        h={"90vh"}
        display={"flex"}
        justifyContent={"center"}
        alignItems={"center"}
      >
        <Spinner />
      </Container>
    );
  }
  if (!fbUser) {
    return <LoginPage />;
  }
  return (
    <>
      {!user && <RegistrationFlow />}
      <Head>
        <title>BPIM2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="4xl" mx="auto" px={4}>
          <Heading fontSize={"2xl"} textAlign={"center"} my={4}>
            BPIM2
          </Heading>
          <Text textAlign={"center"} fontSize={"sm"}>
            おかえりなさい
          </Text>
          <LoginButtons />
          <Separator color="whiteAlpha.400" my={4} />
          <Heading fontSize={"2xl"} textAlign={"center"} my={4}>
            What's BPM2
          </Heading>
        </Container>
      </main>
    </>
  );
}
